# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - nurseai

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://streamlitrg.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_7a55a781b30d409388e70d2b7d6afce4 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_8111070ce16644e480f9b1eaeea3f438 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: streamlitrg.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_7a55a781b30d409388e70d2b7d6afce4 }}/nurseai:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'nurseai'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_e11f5f6f4e5d4fc29409873cd8c75214 }}
        images: 'streamlitrg.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_7a55a781b30d409388e70d2b7d6afce4 }}/nurseai:${{ github.sha }}'